name: test

on: [push]

jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: LS
              run: ls -la
            - name: Setup Node.js environment
              uses: actions/setup-node@v4.4.0

            - name: node version
              run: node --version
            # - name: ls
            #   run: |
            #       chmod +x script.sh
            #       ./script.sh
