name: test

on: [push]

jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: LS
              run: ls -la
            - name: Setup Node.js environment
              uses: actions/setup-node@v4.4.0
              with:
                node-version: latest 

            - name: node version
              run: node --version

            - name: Setup Java JDK
              uses: actions/setup-java@v4.7.1
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: 'maven'
                
            - name: Java version
              run: java --version
            # - name: ls
            #   run: |
            #       chmod +x script.sh
            #       ./script.sh
            # - name: Install dependencies
            #   run: npm install
